import { useEffect, useState } from 'react'
import { Link } from 'react-router'
import { getOverview, searchReservations } from '../lib/admin'
import { restaurantToday } from '../lib/bookingValidation'
import ReservationList from '../components/ReservationList'
import { dayLabel, waiting, shiftDay } from '../lib/reservationDisplay'
import type { ReservationOverview, ReservationPage } from '../types/reservation'
export default function Dashboard() {
 const [date,setDate]=useState(restaurantToday),[service,setService]=useState('dinner'),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0)
 const [data,setData]=useState<{overview:ReservationOverview;pending:ReservationPage;confirmed:ReservationPage}|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 const [,tick]=useState(0)
 useEffect(()=>{const timer=setInterval(()=>tick(x=>x+1),60000);return()=>clearInterval(timer)},[])
 useEffect(()=>{let active=true;void Promise.all([getOverview(date,service),searchReservations({status:'pending',oldest:true,page}),searchReservations({status:'confirmed',from:date,to:date,service})]).then(([overview,pending,confirmed])=>{if(active){setData({overview,pending,confirmed});setLoading(false)}}).catch(()=>{if(active){setError('Impossibile aggiornare le prenotazioni. Riprova.');setLoading(false)}});return()=>{active=false}},[date,service,page,refresh])
 function update(){setPage(0);setError('');setRefresh(x=>x+1)}
 function changeDate(value:string){if(!value)return;setLoading(true);setError('');setDate(value)}
 return <div className="dashboard"><h1 className="sr-only">Dashboard prenotazioni</h1>
 {!loading&&!error&&data&&<div className={`request-alert ${data.overview.pending_total?'attention':''}`}><span className="alert-icon" aria-hidden="true">◷</span><h2>{data.overview.pending_total?`${data.overview.pending_total} richieste da gestire`:'Nessuna richiesta in attesa'}</h2>{data.overview.oldest_at&&<p>La più vecchia da {waiting(data.overview.oldest_at)}</p>}{data.overview.pending_total>0&&<a className="button-primary" href="#pending">Gestisci ora →</a>}</div>}
 <section className="day-controls" aria-label="Giorno e servizio"><div className="date-controls"><button className="button-secondary" aria-label="Giorno precedente" onClick={()=>changeDate(shiftDay(date,-1))}>‹</button><label className="field">{date===restaurantToday()?'Oggi':'Giorno selezionato'}<input aria-label="Giorno" type="date" value={date} onChange={e=>changeDate(e.target.value)}/></label><button className="button-secondary" aria-label="Giorno successivo" onClick={()=>changeDate(shiftDay(date,1))}>›</button></div><div className="service-switch" aria-label="Servizio">{[['lunch','Pranzo'],['dinner','Cena']].map(([k,l])=><button key={k} aria-pressed={service===k} onClick={()=>{if(service!==k){setLoading(true);setError('');setService(k)}}}>{l}</button>)}</div><div className="manual-action"><button className="button-primary" disabled>＋ Nuova prenotazione</button><small>Inserimento manuale non ancora disponibile</small></div></section>
 <div className="panel-heading"><p className="scope-note">{dayLabel(date)} · {service==='lunch'?'Pranzo (prima delle 17:00)':'Cena (dalle 17:00)'} · richieste in attesa di tutte le date</p><button className="button-secondary" disabled={loading} onClick={update}>Aggiorna</button></div>
 {loading?<p className="loading-panel" role="status">Caricamento prenotazioni…</p>:error?<div className="loading-panel"><p role="alert">{error}</p><button className="button-primary" onClick={update}>Riprova</button></div>:data&&<>
 <div className="kpi-grid">{[['Prenotazioni',data.overview.day.total,`di cui ${data.overview.day.pending} da confermare`],['Coperti previsti',data.overview.day.covers,'Confermate + richieste in attesa'],['Da confermare',data.overview.day.pending,'Nel giorno e servizio selezionati'],['Cancellazioni',data.overview.day.cancelled,'Nel giorno e servizio selezionati']].map(([title,value,note])=><section className="kpi-card" key={title}><span className="metric-icon" aria-hidden="true">{title==='Cancellazioni'?'×':'◷'}</span><div><h2>{title}</h2><strong>{value}</strong><p>{note}</p></div></section>)}</div>
 <div className="dashboard-columns"><section className="admin-panel" id="pending"><div className="panel-heading"><h2>Richieste da confermare ({data.pending.total})</h2><small>Prima le più vecchie · tutte le date</small></div><ReservationList rows={data.pending.rows} priority={page===0} onChanged={update}/>{!data.pending.rows.length&&<p className="empty-state">Nessuna richiesta in attesa. Sei in pari.</p>}{data.pending.total>50&&<div className="dashboard-pagination"><button className="button-secondary" disabled={page===0} onClick={()=>{setLoading(true);setPage(x=>x-1)}}>Precedenti</button><span>{page+1} / {Math.ceil(data.pending.total/50)}</span><button className="button-secondary" disabled={(page+1)*50>=data.pending.total} onClick={()=>{setLoading(true);setPage(x=>x+1)}}>Successive</button></div>}</section>
 <section className="admin-panel"><div className="panel-heading"><h2>Prenotazioni confermate</h2><Link to={`/admin/prenotazioni?date=${date}&status=confirmed`}>Vedi tutte →</Link></div><p className="scope-note">{dayLabel(date)} · {service==='lunch'?'Pranzo':'Cena'}</p>{data.confirmed.rows.length?<ol className="confirmed-timeline">{data.confirmed.rows.map(r=><li key={r.id}><time>{r.reservation_time.slice(0,5)}</time><span>{r.first_name} {r.last_name}<small>{r.party_size} persone</small></span><span className="status-badge status-confirmed">Confermata</span></li>)}</ol>:<p className="empty-state">Nessuna prenotazione confermata per questo servizio.</p>}{data.confirmed.total>50&&<p>Prime 50 di {data.confirmed.total}. Apri l’elenco completo con Vedi tutte.</p>}</section></div></>}
 <section className="admin-panel workflow"><h2>Flusso operativo</h2><ol>{[['Richiesta ricevuta','Dal booking online'],['Verifica disponibilità','Valuta personalmente se accettare'],['Conferma o rifiuta','Salva la decisione e contatta il cliente'],['Servizio','Accogli gli ospiti']].map(([t,n],i)=><li key={t}><span>{i+1}</span><div><h3>{t}</h3><p>{n}</p></div></li>)}</ol></section></div>
}
